### ISSUE TITLE
Test SFTtrainer image

### ISSUE THREAD

**Issue by tedhtchang** [foundation-model-stack/fms-hf-tuning#122]
## Is your feature request related to a problem? Please describe.

When Dockerfile is updated no guarantee a tuning job still launch with the pytorchjobs.
For example:
One might assume the `packaging` is not needed and remove it from Dockerfile. The accelerate_launch.py may fail with:
```
│ Traceback (most recent call last):                                                                                                                                                                                        │
│   File "/app/accelerate_launch.py", line 25, in <module>                                                                                                                                                                  │
│     from accelerate.commands.launch import launch_command                                                                                                                                                                 │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/__init__.py", line 16, in <module>                                                                                                                             │
│     from .accelerator import Accelerator                                                                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/accelerator.py", line 35, in <module>                                                                                                                          │
│     from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state                                                                                                       │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/checkpointing.py", line 24, in <module>                                                                                                                        │
│     from .utils import (                                                                                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/utils/__init__.py", line 29, in <module>                                                                                                                       │
│     from .dataclasses import (                                                                                                                                                                                            │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/utils/dataclasses.py", line 34, in <module>                                                                                                                    │
│     from .environment import str_to_bool                                                                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/accelerate/utils/environment.py", line 27, in <module>                                                                                                                    │
│     from packaging.version import parse                                                                                                                                                                                   │
│ ModuleNotFoundError: No module named 'packaging'
```
## Describe the solution you'd like

Create a GH action to test SFT trainer image with every PR. For example: https://gist.github.com/tedhtchang/34335240230d64c6e2ecb5b78d8a8cb0

## Additional context

Add any other context about the feature request here.

**Comment by tedhtchang** [comment]
Not possible to run e2e test. when loading image(12G) into kind, the git action runner ran out disk space.
