### ISSUE TITLE
bug: logging_steps greater than one results in TypeError when evaluating trainer controller rule

### ISSUE THREAD

**Issue by seshapad** [foundation-model-stack/fms-hf-tuning#165]
## Describe the bug

logging_steps greater than one results in TypeError when evaluating trainer controller rule. Following trainer controller configuration used when the bug was detected:
```
controller-metrics:
  - name: loss
    class: Loss
controllers:
  - name: loss-controller
    triggers:
      - on_log
    rule: loss < 1.0
    operations:
      - hfcontrols.should_training_stop
```

## Platform

- Interpreter version: We ran the `./tuning/sft_trainer.py` script with the below training configuration in CCC cluster with 1 GPU (Tesla V100-SXM2-32GB).
- Library version: This environment was not used.

## Sample Code
Below configuration for `fms-hf-tuning` causes the crash:
```
python ./tuning/sft_trainer.py  \
--model_name_or_path $MODEL_PATH  \
--tokenizer_name_or_path $MODEL_PATH \
--training_data_path $DATA_PATH  \
--output_dir $OUTPUT_PATH  \
--validation_data_path $VALIDATION_PATH \
--num_train_epochs 10  \
--per_device_train_batch_size 4  \
--per_device_eval_batch_size 4  \
--gradient_accumulation_steps 4  \
--evaluation_strategy "epoch"  \
--save_strategy "epoch"  \
--learning_rate 1e-5  \
--weight_decay 0.  \
--warmup_ratio 0.03  \
--lr_scheduler_type "cosine"  \
--logging_steps 5  \
--logging_strategy "steps" \
--include_tokens_per_second  \
--packing False  \
--metric_for_best_model "loss" \
--load_best_model_at_end True \
--use_flash_attn False \
--trainer_controller_config_file "examples/trainercontroller_configs/loss.yaml" \
--response_template "\n### Response:"  \
--dataset_text_field "output" 
```

## Expected behavior

The rule should evaluate to False and should not throw any exception.

## Observed behavior
```
  File "/seshapad/fms-hf-tuning/tuning/trainercontroller/callback.py", line 235, in _take_control_actions
    raise TypeError("Rule failed due to incorrect type usage") from et
TypeError: Rule failed due to incorrect type usage
```

## Additional context

None.

**Comment by HarikrishnanBalagopal** [comment]
https://github.com/foundation-model-stack/fms-hf-tuning/blob/04350fa70ccc20317162ae373e838de94a8df6d5/tuning/trainercontroller/callback.py#L234

**Comment by HarikrishnanBalagopal** [comment]
```shell
(/dccstor/rhassistant/seshapad/seshaenv) [haribala@cccxc451 bkp]$ ./run_bug.sh 
deleting output directory
remaking output directory
starting the training
Traceback (most recent call last):
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 369, in <module>
    fire.Fire(main)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 356, in main
    train(
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 134, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3398, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1377, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1458, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: BloomForCausalLM does not support Flash Attention 2.0 yet. Please request to add support where the model is hosted, on its model hub page: https://huggingface.co//dccstor/rhassistant/models/base_models/bloom-560m/discussions/new or in the Transformers GitHub repo: https://github.com/huggingface/transformers/issues/new
./run_bug.sh: line 26: --per_device_train_batch_size: command not found
(/dccstor/rhassistant/seshapad/seshaenv) [haribala@cccxc451 bkp]$ vi ./run_bug.sh 
(/dccstor/rhassistant/seshapad/seshaenv) [haribala@cccxc451 bkp]$ ./run_bug.sh 
deleting output directory
remaking output directory
starting the training
/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:317: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(
/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
 10%|███████████████▍                                                                                                                                          | 3/30 [00:08<01:05,  2.44s/itTraceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 6/7 [00:00<00:00, 15.81it/s]
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/trainercontroller/callback.py", line 224, in _take_control_actions
    rule_succeeded = evaluator.eval(
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 664, in eval
    return super(EvalWithCompoundTypes, self).eval(expr, previously_parsed)
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 428, in eval
    return self._eval(previously_parsed or self.parse(expr))
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 440, in _eval
    return handler(node)
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 443, in _eval_expr
    return self._eval(node.value)
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 440, in _eval
    return handler(node)
  File "/u/haribala/.local/lib/python3.10/site-packages/simpleeval.py", line 519, in _eval_compare
    to_return = self.operators[type(operation)](left, right)
TypeError: '<' not supported between instances of 'NoneType' and 'float'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 369, in <module>
    fire.Fire(main)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 356, in main
    train(
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/sft_trainer.py", line 284, in train
    trainer.train()
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 360, in train
    output = super().train(*args, **kwargs)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer.py", line 2213, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer.py", line 2577, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer.py", line 3387, in evaluate
    self.log(output.metrics)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer.py", line 2956, in log
    self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer_callback.py", line 407, in on_log
    return self.call_event("on_log", args, state, control, logs=logs)
  File "/dccstor/rhassistant/seshapad/seshaenv/lib/python3.10/site-packages/transformers/trainer_callback.py", line 414, in call_event
    result = getattr(callback, event)(
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/trainercontroller/callback.py", line 498, in on_log
    self._actions_on_event(event_name="on_log", **kwargs)
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/trainercontroller/callback.py", line 272, in _actions_on_event
    self._take_control_actions(event_name, **kwargs)
  File "/dccstor/rhassistant/haribala/code/github.com/foundation-model-stack/fms-hf-tuning/tuning/trainercontroller/callback.py", line 234, in _take_control_actions
    raise TypeError("Rule failed due to incorrect type usage") from et
TypeError: Rule failed due to incorrect type usage
 10%|███████████████▍                                                                                                                                          | 3/30 [00:09<01:25,  3.15s/it]
```
